spring:
  application:
    name: payment-service
    logging: debug

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:paymentdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://127.0.0.1:8080/realms/spring-boot-realm}

server:
  port: ${SERVER_PORT:8082}

info:
  app:
    name: Payment Service Application
    version: 1.0.0
    description: DEMO JPA Spring Boot Application with Actuator

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
